formatter: markdown table
output:
  file: README.md
  mode: inject
settings:
  anchor: false
  color: false
  default: true
  description: true
  escape: true
  hide-empty: false
  html: false
  indent: 2
  lockfile: true
  required: true
sort:
  enabled: true
  by: required
